// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5427.robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainfrontLeftMotor;
    public static SpeedController driveTrainfrontRightMotor;
    public static SpeedController driveTrainbackLeftMotor;
    public static SpeedController driveTrainbackRightMotor;
    public static RobotDrive driveTrainRobotDriveController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainfrontLeftMotor = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "frontLeftMotor", (Talon) driveTrainfrontLeftMotor);
        
        driveTrainfrontRightMotor = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "frontRightMotor", (Talon) driveTrainfrontRightMotor);
        
        driveTrainbackLeftMotor = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "backLeftMotor", (Talon) driveTrainbackLeftMotor);
        
        driveTrainbackRightMotor = new Talon(3);
        LiveWindow.addActuator("DriveTrain", "backRightMotor", (Talon) driveTrainbackRightMotor);
        
        driveTrainRobotDriveController = new RobotDrive(driveTrainfrontLeftMotor, driveTrainbackLeftMotor,
              driveTrainfrontRightMotor, driveTrainbackRightMotor);
        
        driveTrainRobotDriveController.setSafetyEnabled(true);
        driveTrainRobotDriveController.setExpiration(0.1);
        driveTrainRobotDriveController.setSensitivity(0.5);
        driveTrainRobotDriveController.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
