package org.usfirst.frc5427.BlakeBot;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap 
{
    public static SpeedController driveTrainFrontRightMotor;
    public static SpeedController driveTrainFrontLeftMotor;
    public static SpeedController driveTrainBackRightMotor;
    public static SpeedController driveTrainBackLeftMotor;
    public static RobotDrive driveTrainRobotDrive4;

    public static void init() 
    {
        driveTrainFrontRightMotor = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "FrontRightMotor", (Talon) driveTrainFrontRightMotor);
        
        driveTrainFrontLeftMotor = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "FrontLeftMotor", (Talon) driveTrainFrontLeftMotor);
        
        driveTrainBackRightMotor = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "BackRightMotor", (Talon) driveTrainBackRightMotor);
        
        driveTrainBackLeftMotor = new Talon(3);
        LiveWindow.addActuator("DriveTrain", "BackLeftMotor", (Talon) driveTrainBackLeftMotor);
        
        driveTrainRobotDrive4 = new RobotDrive(driveTrainFrontLeftMotor, driveTrainBackLeftMotor,driveTrainFrontRightMotor, driveTrainBackRightMotor);
        
        driveTrainRobotDrive4.setSafetyEnabled(true);
        driveTrainRobotDrive4.setExpiration(0.1);
        driveTrainRobotDrive4.setSensitivity(0.5);
        driveTrainRobotDrive4.setMaxOutput(1.0);
        driveTrainRobotDrive4.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainRobotDrive4.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveTrainRobotDrive4.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        driveTrainRobotDrive4.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);


    }
}
